<section class="sub-page-banner text-center" data-stellar-background-ratio="0.3">

    <div class="container">
        <h1 class="entry-title">Aktualności</h1>
        <p>Czytaj najnowsze informacje, bądź na bieżąco z promocjami oraz organizowanymi konkursami w naszych aptekach</p>
    </div>
</section>

<div class="sub-page-content">

    <div class="container">
        <div class="row">
            <div class="col-md-8 blog-wrapper clearfix">
                <h2 class="bordered light">Aktualności</h2>
                <?php if(!empty($news)): ?>

                    <?php /* @var $n \CmsIr\Post\Model\Post */ ?>
                    <?php foreach($news as $n): ?>

                        <?php $date = explode('-', $n->getDate())?>
                        <?php $desc = mb_substr(strip_tags($n->getText()), 0, 200, 'UTF-8') ?>

                        <article class="blog-item blog-full-width">
                            <div class="blog-thumbnail">
                                <img alt="" src="<?php echo $this->basePath() ?>/files/post/<?php echo $n->getFilenameMain() ?>">
                            </div>
                            <div class="blog-full-width-date">
                                <p class="day"><?php echo $date[0] ?></p><p class="monthyear"><?php echo $date[1] . ' ' . $date[2] ?></p>
                            </div>
                            <div class="blog-content">
                                <h4 class="blog-title"><a href="<?php echo $this->url('viewNews', array('slug' => $n->getUrl())) ?>"><?php echo $n->getName() ?></a></h4>
                                <p><?php echo $desc ?></p>
                                <a href="<?php echo $this->url('viewNews', array('slug' => $n->getUrl())) ?>" class="btn btn-default btn-mini btn-rounded">Zobacz</a>
                            </div>
                        </article>

                    <?php endforeach ?>

                <?php endif ?>
            </div>

            <?php echo $this->partial('partial/sidebar') ?>

        </div>
    </div>

    <div class="clr"></div>
</div><!--end sub-page-content-->