<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate("apteka Grodzka")) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        // MAIN CSS (REQUIRED ALL PAGE)
        ->appendStylesheet($this->basePath() . '/css/blue.css')
        ->appendStylesheet($this->basePath() . '/css/medicom.css')
        ->appendStylesheet($this->basePath() . '/css/bootstrap.css')
        ->appendStylesheet($this->basePath() . '/css/jquery-ui-1.10.3.custom.css')
        ->appendStylesheet($this->basePath() . '/css/owl.carousel.css')
        ->appendStylesheet($this->basePath() . '/css/uniform.default.css')
        ->appendStylesheet($this->basePath() . '/css/revolution_style.css')
        ->appendStylesheet($this->basePath() . '/css/settings.css')
        ->appendStylesheet($this->basePath() . '/css/reset.css')
        ->appendStylesheet($this->basePath() . '/css/prettyPhoto.css')
        ->appendStylesheet($this->basePath() . '/css/jcarousel-skin.css')
    ?>
    <!-- Scripts -->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <?php echo $this->headScript()
        ->appendFile($this->basePath() . '/js/jquery.js', 'text/javascript')
        ->appendFile($this->basePath() . '/js/jquery.themepunch.plugins.min.js', 'text/javascript')
        ->appendFile($this->basePath() . '/js/jquery.themepunch.revolution.min.js', 'text/javascript')
    ?>

</head>
<body>
    <div id="wrapper">

        <?php echo $this->partial('partial/layout/header'); ?>

        <?php echo $content; ?>

        <?php echo $this->partial('partial/layout/footer'); ?>

    </div>

    <script type="text/javascript">

        var revapi;

        jQuery(document).ready(function() {

            revapi = jQuery('.tp-banner').revolution(
                {
                    delay:9000,
                    startwidth:1170,
                    startheight:682,
                    hideThumbs:200,
                    fullWidth:"on",
                    forceFullWidth:"on"
                });

        });	//ready

    </script>

    <?php echo $this->inlineScript()
        ->appendFile($this->basePath() . '/js/bootstrap-front.min.js')
        ->appendFile($this->basePath() . '/js/carousel.js')
        ->appendFile($this->basePath() . '/js/jquery.stellar.js')
        ->appendFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.js')
        ->appendFile($this->basePath() . '/js/owl.carousel.js')
        ->appendFile($this->basePath() . '/js/counter.js')
        ->appendFile($this->basePath() . '/js/waypoints.js')
        ->appendFile($this->basePath() . '/js/jquery.uniform.js')
        ->appendFile($this->basePath() . '/js/jquery.prettyPhoto.js')
        ->appendFile($this->basePath() . '/js/forms-validation.js')
        ->appendFile($this->basePath() . '/js/jquery.jcarousel.min.js')
    ?>

    <script type="text/javascript">

        $(function($){
            // parallaax
            $.stellar({
                horizontalScrolling: false,
                verticalOffset: 0
            });

            //date picker
            $("#datepicker").datepicker({
                inline: true
            });
            //owl carousel
            $("#medicom-carousel, #medicom-carousel-1").owlCarousel({
                navigation : true
            });

            //form styling
            $("select").uniform();

            //preetyphotoeffect
            $('a[data-gal]').each(function() {
                $(this).attr('rel', $(this).data('gal'));
            });
            $("a[data-rel^='prettyPhoto']").prettyPhoto({animationSpeed:'slow',theme:'light_square',slideshow:false,overlay_gallery: false,social_tools:false,deeplinking:false});

            //on click show content
            $('.link-more').click(function(e) {
                $('.content-sec').slideDown(1000);
            });
            //on click hide content
            $('.cross').click(function(e) {
                $('.content-sec').slideUp(1000);
            });

        });

    </script>

</body>
</html>
