<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle($this->translate("Demo web-ir website")) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        // MAIN CSS (REQUIRED ALL PAGE)
        ->prependStylesheet($this->basePath() . '/css/main.css')
        ->prependStylesheet($this->basePath() . '/css/style-responsive-frontend.css')
        ->prependStylesheet($this->basePath() . '/css/style-frontend.css')
        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')


        ->prependStylesheet($this->basePath() . '/css/owl.transitions.css')
        ->prependStylesheet($this->basePath() . '/css/owl.theme.css')
        ->prependStylesheet($this->basePath() . '/css/owl.carousel.css')
        ->prependStylesheet($this->basePath() . '/css/magnific-popup.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
    ?>

</head>
<body class="tooltips">
<?php echo $this->partial('partial/layout/header'); ?>
<?php echo $content; ?>
<?php echo $this->partial('partial/layout/footer'); ?>

<?php echo $this->partial('partial/newsletter-modal'); ?>

<!-- BEGIN BACK TO TOP BUTTON -->
<div id="back-top">
    <i class="fa fa-chevron-up"></i>
</div>
<!-- END BACK TO TOP -->

<?php echo $this->inlineScript()
    ->prependFile($this->basePath() . '/js/apps-frontend.js')
    ->prependFile($this->basePath() . '/js/page.js')
    ->prependFile($this->basePath() . '/js/retina.min.js')
    ->prependFile($this->basePath() . '/js/jquery.backstretch.min.js')
    ->prependFile($this->basePath() . '/js/jquery.magnific-popup.min.js')
    ->prependFile($this->basePath() . '/js/owl.carousel.min.js')
    ->prependFile($this->basePath() . '/js/jquery.mixitup.js')
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
?>
<!-- Piwik -->
<script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
        var u="<?php echo $piwik; ?>";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', 1]);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
</script>
<noscript><p><img src="<?php echo $piwik; ?>/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->

</body>
</html>
