<!-- Modal -->
<div class="modal fade" id="deleteMassiveModal" tabindex="-1" role="dialog" aria-hidden="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Usuwanie aptek</h4>
            </div>
            <form action="" method="post">
                <div class="modal-body">
                    <div class="content">
                        <p>
                            Czy na pewno chcesz usunąć wybrane apteki?
                        </p>
                    </div>
                    <div class="message">
                        <p>
                            Zaznacz elementy na liście.
                        </p>
                    </div>
                </div>
                <div class="modal-footer">
                    <img src="/img/ajax-loader.gif" alt="spinner" class="pull-left spinner" />
                    <input type="submit" name="del" value="Anuluj" class="btn btn-default" data-dismiss="modal"/>
                    <input type="submit" name="del" value="Tak" class="btn btn-primary" />
                </div><!-- /.modal-footer -->

            </form>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-doalog -->
</div><!-- /#deleteModal -->